### ISSUE TITLE
api route

### ISSUE THREAD

**Issue by mrzacq** [ajimassaid99/POSBackEnd-CaseStudy#1]
<img width="624" alt="Screenshot 2023-07-04 at 09 08 06" src="https://github.com/ajimassaid99/StudiKasusBackendPOS/assets/58585640/cefa20ba-d27a-4614-8215-14a6c21da876">

ini bisa juga dibuat folder untuk export routes buat nampung api

jadi ga perlu nulis ulang /api berulang kali disini

**Comment by ajimassaid99** [comment]
siap mas
